# Generated by Django 3.2.16 on 2022-10-23 14:33

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('year_published', models.DateField()),
                ('type', models.SmallIntegerField(default=books.models.BookType['two_days'])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
