# Generated by Django 3.2.16 on 2022-10-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Ten Days Loan'), (2, 'Five Days Loan'), (3, 'Two Days Loan')], default=3),
        ),
    ]
